export const SET_FINISHED = "SET_FINISHED";
export const INCREMENT_SCORE = "INCREMENT_SCORE";
export const SET_SELECTED_COLOR = "SET_SELECTED_COLOR";
export const SET_ORIGIN_COLORS = "SET_ORIGIN_COLORS";
